AWSTemplateFormatVersion: '2010-09-09'

Description: "Regional API DNS Setup for Domain"

Parameters:

  Repository:
    Type: String
    AllowedPattern: "^[-_a-zA-Z0-9]+/[-_a-zA-Z0-9]+$"
    ConstraintDescription: |
      Ensure you have defined a full path, including the username or
      organisation name.
    Description: |
      The full name of the repository, such as "<username>/<name>".

  Branch:
    Type: String
    AllowedPattern: "^[-_a-zA-Z0-9]+$"
    ConstraintDescription: |
      Only alpha numeric characters, as well as "-" and "_" are allowed.
    Description: |
      Branch to use from the repository.

Mappings:

  RegionNamesToIDs:
    NorthVirginia:
      Region: us-east-1

Resources:

  NorthVirginiaRegion:
    Type: Custom::GlobalImports
    Properties:
      ServiceToken: !ImportValue GlobalImportValue
      SourceRegion: !FindInMap [ RegionNamesToIDs, NorthVirginia, Region ]
      Exports:
        - 'Key'
        - 'Artifacts'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !ImportValue CodePipelineExecutionRole
      RestartExecutionOnUpdate: true
      ArtifactStores:
        - Region: !Ref AWS::Region
          ArtifactStore:
            Type: S3
            EncryptionKey: 
              Id: !ImportValue Key
              Type: KMS
            Location: !ImportValue Artifacts
        - Region: !FindInMap [ RegionNamesToIDs, NorthVirginia, Region ]
          ArtifactStore:
            Type: S3
            EncryptionKey: 
              Id: !GetAtt NorthVirginiaRegion.Key
              Type: KMS
            Location: !GetAtt NorthVirginiaRegion.Artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: GitHubOutput
              Configuration:
                Owner: !Select [ 0, !Split [ "/", !Ref Repository ] ]
                Repo: !Select [ 1, !Split [ "/", !Ref Repository ] ]
                Branch: !Ref Branch
                OAuthToken: !Sub [ "{{resolve:secretsmanager:${Id}:SecretString:token}}", Id: !ImportValue GitHubSecret ]
                PollForSourceChanges: false
        - Name: Pipeline
          Actions:
            - Name: Update
              RunOrder: 1
              Region: !Ref AWS::Region
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: GitHubOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                RoleArn: !ImportValue CloudFormationExecutionRole
                StackName: !Ref AWS::StackName
                TemplatePath: GitHubOutput::.ci/pipeline.yml
                ParameterOverrides: !Sub |
                  {
                    "Repository": "${Repository}",
                    "Branch": "${Branch}"
                  }

  PipelineTrigger:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration:
        SecretToken: !Ref AWS::StackName
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      Authentication: GITHUB_HMAC
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: !GetAtt Pipeline.Version
      TargetAction: GitHub
      RegisterWithThirdParty: true

Outputs:

  # BuildConsoleURL:
  #   Description: Build URL
  #   Value: !Sub "https://console.aws.amazon.com/codebuild/home?region=${AWS::Region}#/projects/${Build}/view"

  PipelineConsoleURL:
    Description: Pipeline URL
    Value: !Sub "https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}"